sudo: required

services:
  - docker

before_install:
  -

script:
  - docker build -t sinnerschrader/patternplate:$TRAVIS_TAG  .

after_success:
  - if [ "$TRAVIS_TAG" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sinnerschrader/patternplate;
    fi